---
- name: Backup DSTUCK
  hosts: 10.15.8.41
  gather_facts: false
  vars:
    backup_dir: "/home/awxadmin/playbooks/backups/41"
  collections:
    - dellemc.os6
  tasks:
    - name: Backup
      os6_config:
        backup: yes
        backup_options:
          dir_path: "{{ backup_dir }}"
