---
- name: Backup DNOS10
  hosts: dellos10
  gather_facts: false
#  vars:
#    backup_dir: "/home/awxadmin/"
#  collections:
#    - dellemc.os10
  tasks:
    - name: Backup
      os10_config:
        backup: yes
        backup_options:
          dir_path: "{{ backup_dir }}"
