---
- name: Backup DNOS10
  hosts: 10.15.8.31
  gather_facts: false
  vars:
    backup_dir: "/home/awxadmin/playbooks/backups/10"
  collections:
    - dellemc.os10
  tasks:
    - name: Backup
      os10_config:
        backup: yes
        backup_options:
          dir_path: "{{ backup_dir }}"
